### ISSUE TITLE
Lifetime on statement disallow the storage of statement in struct alongside it's connection.

### ISSUE THREAD

**Issue by Ort1e** [stainless-steel/sqlite#103]
I want to be able to do something like that :
```rust
pub struct Wrapper<'a> {
    connection : Connection,
    statement : Statement<'a>
}
```
And in a constructor :
```rust
pub fn new<P1: AsRef<Path> >(db_path : P1) -> Wrapper<'a> {
       
        let connection = Connection::open(db_path).unwrap();

         Wrapper {
            connection : connection,
            statement : connection.prepare(QUERY).unwrap()
        }
    }
```
But the borrow checker is not happy and trigger a borrow error `"connection" dropped here while still borrowed`. 'Here' is at the end of the function.

I checked the definition of prepare method : 
```rust
pub fn prepare<T: AsRef<str>>(&self, statement: T) -> Result<Statement<'_>> {
        crate::statement::new(self.raw.0, statement)
    }
``` 
And I don't know why the statement has the lifetime `_ and not linked to the lifetime of self ?

**Comment by ReactorScram** [comment]
I know this is closed, but I ran into the same problem, and I saw the rusqlite community has a similar problem.

`rusqlite` solves it with `CachedStatement`, but they also separate `Statement` into `Statement` and `Rows` which is less ergonomic for apps that want to return iterators to their callers.

@IvanUkhov If I made a PR for the following plan, would you check it out?

1. Add a `BTreeMap<u64, Statement>` that lives inside `sqlite::Connection`, and somehow don't include the `PhantomData`, so that library-managed statements are exempt from the self-borrowing problem.
2. Add `Connection::prepare_handle` which generates a random u64 handle, associates it to the prepared statement, and returns just the handle. The handle has no methods of its own.
3. Add `Connection::borrow_statement` which takes a handle and borrows a prepared statement from the `BTreeMap`.

That gets 80% of the way to caching with 20% of the code. We can use `sqlite3_randomness` to generate handles without pulling in any new deps. The reason for them to be random is to throw errors if a caller accidentally gets a handle from one `Connection` and tries to use it on another `Connection`.

If I forget to come back to it, someone else should execute that plan lol

**Comment by ReactorScram** [comment]
I started on my idea, but it's a big change, and it interferes with the `Cursor` module so I commented that out: https://github.com/ReactorScram/sqlite/commit/1bd112e4edd406ee42cf65af28e5e705342886dc

My theory is that since the `Statement` can never truly be independent of the `Connection` that created it, we should treat the `Connection` as an arena or ECS-like object which owns its `Statement` instances, and callers can only borrow them or tell `Connection` what to do to a `Statement`.

I might just fork this into a separate sqlite wrapper crate.

## Details

The problem I'm seeing is that the SQLite C API has the wrong 'shape' to it, and it works in unsafe C code, but it doesn't fit into Rust.

The C API is a "graph of pointers" where the caller pretends that everything is elegant and self-contained, but for the sake of a 'simple' API, the SQL statements actually contain a pointer back to their owning connection: https://github.com/sqlite/sqlite/blob/cfab83477533d12a01303e3f73eec7e3a8ef5e9f/src/vdbeapi.c#L112-L113

In Rust code we'd say that you can't have a pointer back to the object that created you, it leads to trouble, if the child object depends on the parent then it should be owned by the parent.

The same problem has come up when adapting GUI frameworks built for C/C++ "graph of self-contained-but-not-really pointer objects" like Qt into Rust.

My idea has the usual problem that the handle pattern / arena pattern has - You can tell `Connection` to drop a statement and then use the `Handle` anyway, and this results in a logic error, which is memory safe and throws an error 99.9% of the time but the other 0.1% (probably less, it has to be a `usize` collision) it does something nonsensical instead of throwing.
